### ISSUE TITLE
About dataloader ERROR

### ISSUE THREAD

**Issue by JiangPeiy** [z-bingo/FastDVDNet#5]
C:\Users\Win10\Desktop\unet-master\venv\Scripts\python.exe C:/Users/Win10/Desktop/unet-master/FastDVD-master/train_eval.py
Namespace(batch_size=64, cuda=False, dataset_path='F:/JPY/vimeo_triplet/sequences', eval=False, frames=2, im_size=96, learning_rate=0.0001, max_epoch=100, num_worker=4, restart=False, txt_path='F:/JPY/vimeo_triplet')
There is no any model to load, restart the train process.
Traceback (most recent call last):
  File "C:/Users/Win10/Desktop/unet-master/FastDVD-master/train_eval.py", line 200, in <module>
    train(args)
  File "C:/Users/Win10/Desktop/unet-master/FastDVD-master/train_eval.py", line 92, in train
    for iter, (data, gt) in enumerate(data_loader):
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Win10\Desktop\unet-master\FastDVD-master\data_provider.py", line 50, in __getitem__
    img = Image.open(file)
  File "C:\Users\Win10\Desktop\unet-master\venv\lib\site-packages\PIL\Image.py", line 2912, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'F:/JPY/vimeo_triplet/sequences\\00068/0821\\im4.png'

Process finished with exit code 1

**Comment by JiangPeiy** [comment]
Can you help me with this question?
